// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFAToKntOoDJC0aHjrhKey8c4_oTr9zxQ',
    appId: '1:315653337697:web:854744f075d0a7eccc7020',
    messagingSenderId: '315653337697',
    projectId: 'activity-tracker-8a456',
    authDomain: 'activity-tracker-8a456.firebaseapp.com',
    storageBucket: 'activity-tracker-8a456.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5piG4zOVzs7Tx2KW5il5PAUBVwYVNYiA',
    appId: '1:315653337697:android:d60c67556e305c5ecc7020',
    messagingSenderId: '315653337697',
    projectId: 'activity-tracker-8a456',
    storageBucket: 'activity-tracker-8a456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmUNg2ZjnlxsLCYjyapCjQuFLZKAh32Q',
    appId: '1:315653337697:ios:ef521e9a891cb788cc7020',
    messagingSenderId: '315653337697',
    projectId: 'activity-tracker-8a456',
    storageBucket: 'activity-tracker-8a456.appspot.com',
    iosBundleId: 'com.example.activityTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmUNg2ZjnlxsLCYjyapCjQuFLZKAh32Q',
    appId: '1:315653337697:ios:d9dbf4b2830bf406cc7020',
    messagingSenderId: '315653337697',
    projectId: 'activity-tracker-8a456',
    storageBucket: 'activity-tracker-8a456.appspot.com',
    iosBundleId: 'com.example.activityTracker.RunnerTests',
  );
}
